# This workflow allows GitHub Actions to automagically update your app
# whenever a new upstream release is detected.
# You need to enable Actions in your repository settings.
# This file should be enough by itself, but feel free to tune it to your needs.
# It calls updater.sh, which is where you should put the app-specific update steps.
name: Check for new upstream releases
on:
  # Allow to manually trigger the workflow
  workflow_dispatch:
  # Run it every day at 6:00 UTC
  schedule:
    - cron:  '0 6 * * *'
jobs:
  updater:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the source code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if newer version is available upstream
        id: check_version
        run: |
          # Install moreutils, needed for sponge
          sudo apt-get install moreutils
          # Fetching information
          current_version=$(cat manifest.json | jq -j '.version|split("~")[0]')
          repo=$(cat manifest.json | jq -j '.upstream.code|split("https://github.com/")[1]')
          version=$(curl --silent "https://api.github.com/repos/$repo/releases" | jq -r '.[] | .tag_name' | sort -V | tail -1)
          assets=$(curl --silent "https://api.github.com/repos/$repo/releases" | jq -r '[ .[] | select(.tag_name=="'$version'").assets[].browser_download_url ] | join(" ") | @sh' | tr -d "'")
          # Setting up the environment variables
          echo ::set-output name=current_version::$current_version
          echo "Current version: $current_version"
          echo ::set-output name=latest_version::$version
          echo "Latest release from upstream: $version"
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "ASSETS=$assets" >> $GITHUB_ENV
          if ! dpkg --compare-versions "$current_version" "lt" "$version" ; then
            echo "PROCEED=false" >> $GITHUB_ENV
            echo "::warning ::No new version available"
          elif git ls-remote -q --exit-code --heads https://github.com/$GITHUB_REPOSITORY.git ci-auto-update-v$version ; then
            echo "PROCEED=false" >> $GITHUB_ENV
            echo "::warning ::A branch already exists for this update"
          else
            echo "PROCEED=true" >> $GITHUB_ENV
          fi
      - name: Update package files
        id: update_files
        if: ${{ env.PROCEED == 'true' }}
        run: |
          # Setting up Git user
          git config --global user.name 'yunohost-bot'
          git config --global user.email 'yunohost-bot@users.noreply.github.com'
          # Run the version updater script
          ./.github/workflows/updater.sh
          retval=$?
          # Check
          if [ $retval -neq 0 ]; then
              echo "PROCEED=false" >> $GITHUB_ENV
              echo "::warning ::The updater script failed (exit code $retval)"
          fi
          # Replace new version in manifest
          jq -s --indent 4 ".[] | .version = \"$VERSION~ynh1\"" manifest.json | sponge manifest.json
          # Commit
          git commit -am "Upgrade to v$VERSION"
      - name: Create Pull Request
        id: cpr
        if: ${{ env.PROCEED == 'true' }}
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update to version ${{ env.VERSION }}
          committer: 'yunohost-bot <yunohost-bot@users.noreply.github.com>'
          author: 'yunohost-bot <yunohost-bot@users.noreply.github.com>'
          signoff: false
          branch: ci-auto-update-v${{ env.VERSION }}
          delete-branch: true
          title: 'Upgrade to version ${{ env.VERSION }}'
          body: |
            Upgrade to v${{ env.VERSION }}
          draft: false
      - name: Check outputs
        if: ${{ env.PROCEED == 'true' }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
          echo "Current version - ${{ steps.check_version.outputs.current_version }}"
          echo "New version - ${{ steps.check_version.outputs.latest_version }}"
